services:
  postgres:
    image: postgres:16
    container_name: shock_systems
    restart: unless-stopped
    environment:
      POSTGRES_USER: shock
      POSTGRES_PASSWORD: shock123
      POSTGRES_DB: shock_db
    ports:
      - "5433:5432"
    volumes:
      - shock_systems_data:/var/lib/postgresql/data

volumes:
  shock_systems_data:
